### PR TITLE
City Council

### PR DESCRIPTION
**Pull request by neortls007idev**
City Council - Kempsvile added
Mayors Added.

### CODE REVIEW

**Comment by stanzheng** [comment]
Hi @neortls007idev thanks for the help!

 could you follow the pattern of naming the images the last name of the candidate the same as here

https://github.com/Code4HR/okcandidate/tree/develop/assets/img/candidates

**Comment by neortls007idev** [comment]
OK i'll rename them

**Comment by neortls007idev** [comment]
Btw any special folder you want it in?

**Comment by stanzheng** [comment]
hi @neortls007idev you can drop them in the /assets/img/candidates folder linked here 

https://github.com/Code4HR/okcandidate/tree/develop/assets/img/candidates

**Comment by neortls007idev** [comment]
ok all done with appropriate name and path.

**Pull request merged**
