### PR TITLE
Improve grammar

### PR DESCRIPTION
**Pull request by ryayak1460**
Since some of the questions either didn't seem to make sense when
combined with the intensity rating or had wording which may not have had
clear meanings, improve the grammar of some of the questions and answers
so we can have more consistent survey data and user experiences.

Signed-off-by: Ryan Y <ryayak1460@protingumas.com>

### CODE REVIEW

**Comment by stanzheng** [comment]
> 'Have you ridden public transit in the past three months'
>'Would you ride public transit in the near future?'),

I think the adjustment changes the question. What if we changed ridden to used or something of the lack

**Comment by ryayak1460** [comment]
The problem lies in that "how strongly do you feel about this" makes no sense for the original question.  Using `used` instead doesn't really help much either.

What else would work here?

**Comment by stanzheng** [comment]
Agree with you, the question probably needs to be reworked in general.

**Comment by ryayak1460** [comment]
Okay.  Let me know tonight or tomorrow what to change it to if you have any suggestions and I'll commit again.

**Comment by kmcurry** [comment]
Be sure to check the G-form so we stay in Sync. G-form is "master". I'll
work on that queations

On Friday, April 1, 2016, Ryan Y. <notifications@github.com> wrote:

> Okay. Let me know tonight or tomorrow what to change it to if you have any
> suggestions and I'll commit again.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Code4HR/okcandidate/pull/60#issuecomment-204600698>
>


-- 
Kevin Curry
Virginia Beach, VA
https://comparityins.com

**Comment by kmcurry** [comment]
The challenge you are facing comes from changing the rating question to "How strongly do you feel about this?" The original was "How important is public transportation to you?" Public transportation can be important or not important regardless of whether the respondent uses it regularly or at all. I'm conflicted about switching from "How important" to "How strongly do you feel" but I'm pretty certain the rating question should restate the choice question instead of using the ambiguous "this"

**Pull request closed without merging**
