### PR TITLE
Loading indicator

### PR DESCRIPTION
**Pull request by ryayak1460**
The following changes since commit d7f20848642471af5dad384eb8dc4e75070a55dd:

  Merge pull request #128 from wbprice/127-candidates-should-be-sorted-by-match-score (2016-04-19 21:15:20 -0400)

are available in the git repository at:

  https://github.com/ryayak1460/okcandidate.git loading-indicator

for you to fetch changes up to c47e03cfdde4c475ef0264cb140884d85c18c4c4:

  Mock survey page dependencies in examples (2016-04-20 12:56:27 -0400)

----------------------------------------------------------------
Ryan Y (4):
      Create loading indicator component
      Replace generic loading message with indicator
      Remove spinner
      Mock survey page dependencies in examples

 assets/js/components/atoms/LoadingIndicator.jsx    | 17 +++++
 assets/js/components/ecosystems/SurveyPage.jsx     | 11 ++--
 .../components/atoms/LoadingIndicatorSpec.js       | 73 ++++++++++++++++++++
 .../components/ecosystems/SurveyPageSpec.js        | 77 ++++++++++++++++++++++
 4 files changed, 174 insertions(+), 4 deletions(-)
 create mode 100644 assets/js/components/atoms/LoadingIndicator.jsx
 create mode 100644 test/frontend/components/atoms/LoadingIndicatorSpec.js
 create mode 100644 test/frontend/components/ecosystems/SurveyPageSpec.js

### CODE REVIEW

**Comment by ryayak1460** [comment]
Affects #107.

**Comment by wbprice** [comment]
@ryayak1460 This works locally, but you're missing some dependencies in package.json and now there are merge conflicts.  Please update your PR.

**Comment by ryayak1460** [comment]
Which dependencies are missing?

On 22 April 2016 11:25:11 GMT-04:00, "W. Blaine Price" <notifications@github.com> wrote:
>@ryayak1460 This works locally, but you're missing some dependencies in
>package.json and now there are merge conflicts.  Please update your PR.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Code4HR/okcandidate/pull/131#issuecomment-213472313

-- 
Ryan Y.
Software Design Engineer
Alion Science and Technology Corporation
GnuPG Key: 0x358CD775
VoIP (ZRTP-encrypted): ryayak1460@ostel.co
IM (OTR encryption): ryayak1460@dukgo.com

**Comment by wbprice** [comment]
@ryayak1460 At least `style-loader' and  'css-loader`.  Try to clone to a new directory and `npm install` to see if there are any others that might be missing.

**Comment by wbprice** [comment]
@ryayak1460 Looks good!  My only feedback is that I'd like to see this loading indicator used in `ecosystems/ResultsPage.jsx` as well.  Rules for displaying the loading indicator are similar.

**Comment by ryayak1460** [comment]
Okay, I'll get on that when I get back from lunch.  Thanks, @wbprice!

On 22 April 2016 12:14:58 GMT-04:00, "W. Blaine Price" <notifications@github.com> wrote:
>@ryayak1460 Looks good!  My only feedback is that I'd like to see this
>loading indicator used in `ecosystems/ResultsPage.jsx` as well.  Rules
>for displaying the loading indicator are similar.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Code4HR/okcandidate/pull/131#issuecomment-213495555

-- 
Ryan Y.
Software Design Engineer
Alion Science and Technology Corporation
GnuPG Key: 0x358CD775
VoIP (ZRTP-encrypted): ryayak1460@ostel.co
IM (OTR encryption): ryayak1460@dukgo.com

**Comment by wbprice** [comment]
LTGM

**Pull request merged**
